export const TabStrip = {
  id: 10,
  name: "TabStrip1",
  type: "TabStrip",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  multiRow: false,
  picture: "(None)",
  tabFixedHeight: 21,
  tabFixedWidth: 32,
  tabindex: 13,
  tabOrientation: "0 - fmTabOrientationTop",
  tabStop: true,
  tag: "",
  value: "",
  style1:"0 - fmTabStyleTabs",
  visible: true,
  style: {
    // left: "20px",
    // top: "100px",
    width: "284px",
    height: "140px",
    // zIndex: "1",
    // backgroundColor: "white",
    // fontFamily: "Arial, Helvetica, sans-serif",
    // color: "black",
    // cursor: "default",
  },
};
